# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cdm.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'cdm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcdm.proto\x12\x0b\x66imex_index\"\xaa\x01\n\x07\x43\x44MData\x12+\n\tdata_type\x18\x01 \x01(\x0e\x32\x18.fimex_index.CDMDataType\x12\x12\n\nvalues_u32\x18\x04 \x03(\x07\x12\x12\n\nvalues_u64\x18\x05 \x03(\x06\x12\x12\n\nvalues_f32\x18\x06 \x03(\x02\x12\x12\n\nvalues_f64\x18\x07 \x03(\x01\x12\x0f\n\x07strings\x18\x08 \x03(\r\x12\x11\n\tvalues_u8\x18\t \x01(\x0c\"@\n\x0c\x43\x44MAttribute\x12\x0c\n\x04name\x18\x01 \x01(\r\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.fimex_index.CDMData\"B\n\x0c\x43\x44MDimension\x12\x0c\n\x04name\x18\x01 \x01(\r\x12\x0e\n\x06length\x18\x02 \x01(\r\x12\x14\n\x0cis_unlimited\x18\x03 \x01(\x08\"}\n\x0b\x43\x44MVariable\x12\x0c\n\x04name\x18\x01 \x01(\r\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.fimex_index.CDMData\x12\r\n\x05shape\x18\x03 \x03(\r\x12-\n\nattributes\x18\x04 \x03(\x0b\x32\x19.fimex_index.CDMAttribute\"\xa8\x01\n\x03\x43\x44M\x12\x0f\n\x07strings\x18\x01 \x03(\t\x12-\n\ndimensions\x18\x02 \x03(\x0b\x32\x19.fimex_index.CDMDimension\x12+\n\tvariables\x18\x03 \x03(\x0b\x32\x18.fimex_index.CDMVariable\x12\x34\n\x11global_attributes\x18\x04 \x03(\x0b\x32\x19.fimex_index.CDMAttribute*\xd0\x01\n\x0b\x43\x44MDataType\x12\x0b\n\x07\x43\x44M_NAT\x10\x00\x12\x0c\n\x08\x43\x44M_CHAR\x10\x01\x12\r\n\tCDM_SHORT\x10\x02\x12\x0b\n\x07\x43\x44M_INT\x10\x03\x12\r\n\tCDM_FLOAT\x10\x04\x12\x0e\n\nCDM_DOUBLE\x10\x05\x12\x0e\n\nCDM_STRING\x10\x06\x12\r\n\tCDM_UCHAR\x10\x07\x12\x0e\n\nCDM_USHORT\x10\x08\x12\x0c\n\x08\x43\x44M_UINT\x10\t\x12\r\n\tCDM_INT64\x10\n\x12\x0e\n\nCDM_UINT64\x10\x0b\x12\x0f\n\x0b\x43\x44M_STRINGS\x10\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cdm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CDMDATATYPE']._serialized_start=632
  _globals['_CDMDATATYPE']._serialized_end=840
  _globals['_CDMDATA']._serialized_start=27
  _globals['_CDMDATA']._serialized_end=197
  _globals['_CDMATTRIBUTE']._serialized_start=199
  _globals['_CDMATTRIBUTE']._serialized_end=263
  _globals['_CDMDIMENSION']._serialized_start=265
  _globals['_CDMDIMENSION']._serialized_end=331
  _globals['_CDMVARIABLE']._serialized_start=333
  _globals['_CDMVARIABLE']._serialized_end=458
  _globals['_CDM']._serialized_start=461
  _globals['_CDM']._serialized_end=629
# @@protoc_insertion_point(module_scope)
