# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grib_index.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'grib_index.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cdm_pb2 as cdm__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10grib_index.proto\x12\x0b\x66imex_index\x1a\tcdm.proto\"L\n\tGribChunk\x12\x12\n\nfile_index\x18\x01 \x01(\r\x12\x15\n\rmessage_start\x18\x02 \x01(\x04\x12\x14\n\x0cmessage_size\x18\x03 \x01(\r\"n\n\x0cGribVariable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cscale_factor\x18\x02 \x01(\x01\x12\x12\n\nadd_offset\x18\x03 \x01(\x01\x12&\n\x06\x63hunks\x18\x04 \x03(\x0b\x32\x16.fimex_index.GribChunk\"g\n\tGribIndex\x12\x1d\n\x03\x63\x64m\x18\x01 \x01(\x0b\x32\x10.fimex_index.CDM\x12\r\n\x05\x66iles\x18\x02 \x03(\t\x12,\n\tvariables\x18\x03 \x03(\x0b\x32\x19.fimex_index.GribVariableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grib_index_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRIBCHUNK']._serialized_start=44
  _globals['_GRIBCHUNK']._serialized_end=120
  _globals['_GRIBVARIABLE']._serialized_start=122
  _globals['_GRIBVARIABLE']._serialized_end=232
  _globals['_GRIBINDEX']._serialized_start=234
  _globals['_GRIBINDEX']._serialized_end=337
# @@protoc_insertion_point(module_scope)
