# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: netcdf_index.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'netcdf_index.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cdm_pb2 as cdm__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12netcdf_index.proto\x12\x0b\x66imex_index\x1a\tcdm.proto\"M\n\x0bNetCDFChunk\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x0e\n\x06offset\x18\x03 \x03(\x04\x12\x12\n\nfile_index\x18\x04 \x01(\r\"\x0f\n\rFilterShuffle\"\x0f\n\rFilterDeflate\"n\n\nFilterSzip\x12\x11\n\tnn_coding\x18\x01 \x01(\x08\x12\x18\n\x10pixels_per_block\x18\x02 \x01(\r\x12\x16\n\x0e\x62its_per_pixel\x18\x03 \x01(\r\x12\x1b\n\x13pixels_per_scanline\x18\x04 \x01(\r\"5\n\rFilterGeneric\x12\x11\n\tfilter_id\x18\x01 \x01(\r\x12\x11\n\tcd_values\x18\x02 \x03(\r\"\xc6\x01\n\x06\x46ilter\x12-\n\x07shuffle\x18\x01 \x01(\x0b\x32\x1a.fimex_index.FilterShuffleH\x00\x12-\n\x07\x64\x65\x66late\x18\x02 \x01(\x0b\x32\x1a.fimex_index.FilterDeflateH\x00\x12\'\n\x04szip\x18\x03 \x01(\x0b\x32\x17.fimex_index.FilterSzipH\x00\x12-\n\x07generic\x18\x04 \x01(\x0b\x32\x1a.fimex_index.FilterGenericH\x00\x42\x06\n\x04kind\"\xaf\x01\n\x0eNetCDFVariable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_shape\x18\x02 \x03(\x04\x12*\n\nbyte_order\x18\x03 \x01(\x0e\x32\x16.fimex_index.ByteOrder\x12(\n\x06\x63hunks\x18\x04 \x03(\x0b\x32\x18.fimex_index.NetCDFChunk\x12$\n\x07\x66ilters\x18\x05 \x03(\x0b\x32\x13.fimex_index.Filter\"k\n\x0bNetCDFIndex\x12\x1d\n\x03\x63\x64m\x18\x01 \x01(\x0b\x32\x10.fimex_index.CDM\x12\r\n\x05\x66iles\x18\x02 \x03(\t\x12.\n\tvariables\x18\x03 \x03(\x0b\x32\x1b.fimex_index.NetCDFVariable*1\n\tByteOrder\x12\x11\n\rBYTE_ORDER_LE\x10\x00\x12\x11\n\rBYTE_ORDER_BE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'netcdf_index_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BYTEORDER']._serialized_start=814
  _globals['_BYTEORDER']._serialized_end=863
  _globals['_NETCDFCHUNK']._serialized_start=46
  _globals['_NETCDFCHUNK']._serialized_end=123
  _globals['_FILTERSHUFFLE']._serialized_start=125
  _globals['_FILTERSHUFFLE']._serialized_end=140
  _globals['_FILTERDEFLATE']._serialized_start=142
  _globals['_FILTERDEFLATE']._serialized_end=157
  _globals['_FILTERSZIP']._serialized_start=159
  _globals['_FILTERSZIP']._serialized_end=269
  _globals['_FILTERGENERIC']._serialized_start=271
  _globals['_FILTERGENERIC']._serialized_end=324
  _globals['_FILTER']._serialized_start=327
  _globals['_FILTER']._serialized_end=525
  _globals['_NETCDFVARIABLE']._serialized_start=528
  _globals['_NETCDFVARIABLE']._serialized_end=703
  _globals['_NETCDFINDEX']._serialized_start=705
  _globals['_NETCDFINDEX']._serialized_end=812
# @@protoc_insertion_point(module_scope)
