#!/usr/bin/env python3
"""
patch_index_files.py — Patch filenames stored in fimex protobuf index files.

Reads a GRIB (.grbfp) or NetCDF (.ncfp) protobuf index, replaces a prefix in
every source filename (files[1:]), and writes the result back in-place (or to a
separate output file).

Usage
-----
    patch_index_files.py [options] INDEX [INDEX ...]

    --old-prefix OLD   Prefix to remove from every filename (may be empty).
    --new-prefix NEW   Prefix to prepend after removing the old prefix (may be empty).
    --output OUTPUT    Write patched index to OUTPUT instead of modifying in-place.
                       Only valid when a single INDEX is given.

The script fails (exit 1) if any stored filename does not start with OLD prefix.

The virtualenv in .venv/ next to this script must contain the protobuf package.
The _pb2.py stubs (cdm_pb2, grib_index_pb2, netcdf_index_pb2) must live in the
same directory as this script (generated by grpc_tools.protoc / protoc).

Magic layout (8 bytes total, written before the serialised protobuf body)
-------------------------------------------------------------------------
  bytes 0-7  FIMEX_PROTO_INDEX_MAGIC  b'FMXIDX\x00P'
  bytes 8-11 format discriminator     b'G\x00\x00\x00' (GRIB) or b'N\x00\x00\x00' (NetCDF)
"""

import argparse
import struct
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Magic constants (must match ProtobufCDM.cc / GribProtobufIndexWriter.cc /
# NetCDFProtobufIndexWriter.cc)
# ---------------------------------------------------------------------------
FIMEX_MAGIC = b"FMXIDX\x00P"  # 8 bytes
GRIB_MAGIC = b"G\x00\x00\x00"  # 4 bytes
NC_MAGIC = b"N\x00\x00\x00"  # 4 bytes
HEADER_SIZE = len(FIMEX_MAGIC) + 4  # 12 bytes total


# ---------------------------------------------------------------------------
# Prefix-replacement function wrapped in a callable class for clean config
# ---------------------------------------------------------------------------
class PrefixReplacer:
    """Replace a fixed prefix in filenames, failing on mismatch."""

    def __init__(self, old_prefix: str, new_prefix: str):
        self.old_prefix = old_prefix
        self.new_prefix = new_prefix

    def __call__(self, filename: str) -> str:
        if not filename.startswith(self.old_prefix):
            raise ValueError(
                f"Filename {filename!r} does not start with "
                f"old-prefix {self.old_prefix!r}"
            )
        return self.new_prefix + filename[len(self.old_prefix) :]


# ---------------------------------------------------------------------------
# Index type detection
# ---------------------------------------------------------------------------
def detect_type(data: bytes) -> str:
    """Return 'grib', 'netcdf', or raise ValueError."""
    if len(data) < HEADER_SIZE:
        raise ValueError("File too small to be a fimex protobuf index")
    if data[: len(FIMEX_MAGIC)] != FIMEX_MAGIC:
        raise ValueError("FIMEX_PROTO_INDEX_MAGIC mismatch — not a fimex index")
    fmt = data[len(FIMEX_MAGIC) : HEADER_SIZE]
    if fmt == GRIB_MAGIC:
        return "grib"
    if fmt == NC_MAGIC:
        return "netcdf"
    raise ValueError(f"Unknown format discriminator: {fmt!r}")


# ---------------------------------------------------------------------------
# Patch a single index file
# ---------------------------------------------------------------------------
def patch_index(path: Path, replacer: PrefixReplacer, output: Path | None) -> None:
    data = path.read_bytes()
    kind = detect_type(data)
    body = data[HEADER_SIZE:]

    # Import the correct generated stub
    if kind == "grib":
        import grib_index_pb2

        msg = grib_index_pb2.GribIndex()
    else:
        import netcdf_index_pb2

        msg = netcdf_index_pb2.NetCDFIndex()

    msg.ParseFromString(body)

    # files[0] is always the empty sentinel; patch files[1:]
    if len(msg.files) == 0:
        print(f"{path}: no 'files' entries — nothing to patch", file=sys.stderr)
        return

    for i, fname in enumerate(msg.files):
        if i == 0:
            continue  # sentinel, always empty
        msg.files[i] = replacer(fname)

    new_body = msg.SerializeToString()
    dest = output if output is not None else path
    dest.write_bytes(data[:HEADER_SIZE] + new_body)
    print(f"Patched {path} → {dest}  ({kind}, {len(msg.files) - 1} filename(s))")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(
        description="Patch source filenames in fimex GRIB/NetCDF protobuf index files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "index",
        nargs="+",
        metavar="INDEX",
        help="Protobuf index file(s) to patch (.grbfp or .ncfp)",
    )
    parser.add_argument(
        "--old-prefix",
        default="",
        metavar="OLD",
        help="Prefix to strip from each stored filename (default: empty)",
    )
    parser.add_argument(
        "--new-prefix",
        default="",
        metavar="NEW",
        help="Prefix to prepend after stripping (default: empty)",
    )
    parser.add_argument(
        "--output",
        metavar="OUTPUT",
        help="Write result to OUTPUT instead of in-place "
        "(only valid with a single INDEX)",
    )
    args = parser.parse_args()

    if args.output and len(args.index) != 1:
        parser.error("--output can only be used with a single INDEX file")

    replacer = PrefixReplacer(args.old_prefix, args.new_prefix)
    output = Path(args.output) if args.output else None

    errors = 0
    for idx_path in args.index:
        try:
            patch_index(Path(idx_path), replacer, output)
        except Exception as exc:
            print(f"ERROR: {idx_path}: {exc}", file=sys.stderr)
            errors += 1

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
