Document: fimex
Title: Debian fimex Manual
Author: <insert document author here>
Abstract: This manual describes what fimex is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fimex/fimex.sgml.gz

Format: postscript
Files: /usr/share/doc/fimex/fimex.ps.gz

Format: text
Files: /usr/share/doc/fimex/fimex.text.gz

Format: HTML
Index: /usr/share/doc/fimex/html/index.html
Files: /usr/share/doc/fimex/html/*.html

  
